### ISSUE TITLE
Bug report: Specific AT pages should have global country option showing global data

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#1]
## The problem ##
When user clicks the dropdown menu for "filter by country", there is no choice for "global". Instead, there are two options, "bangladesh" and "colombia"

## Help us reproduce the problem ##

**Steps to reproduce the behaviour:**

1. Go to AT Pages
2. Click on Open the country selector while AT is filtered to limb prosthetics, and set the filter to "global".

**Add screenshots** 
![Picture1](https://github.com/Daniel-GDI-Hub/data-portal/assets/133969226/028e1013-2f2b-4a52-9adb-ad6920d1feca)

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser Chrome
 -  Version 

**Smartphone (please complete the following information):**

**Additional context**

## The expectation

The results page shows all data available for limb prosthetics world-wide.

**Comment by matthew-gibbs** [comment]
This is because the first filter is set to 'Limb Prosthetics' which only has 2 studies, one conducted in Bangladesh, and one in Columbia, so there is no 'Global' study here.

**Comment by Daniel-UCL** [comment]
Yes, this links to Issue #5 and Issue #2. To solve this issue, changing the behaviour of the filters (issue 5 comment), and introducing a separate data set for global data would be enough I think. For discussion though.

**Comment by Daniel-UCL** [comment]
Found alternative solution, and included global data in AT summary paragraph.
