### ISSUE TITLE
Feature request: Visualisation and “love data” link

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#10]
## The problem

When I scroll down to the "quick links" section. Click the link titled "Love data? We do", I thought at first the data was for the chart so the detailed data would be just below it. I thought the rich screenreader view was the detailed one.

## The solution

Clarify terminology and set better expectation around data, data visulisation and its accessability features.  

## The alternatives

**Describe alternatives you've considered**

## Additional info

**Additional context**

**Comment by matthew-gibbs** [comment]
Not sure I understand - is this one just a text change?

**Comment by Daniel-UCL** [comment]
This is a minor UX issue reported by a single tester. We believe the confusion arises from the layout of the data visualisation, and the link talking about the data source. The wrong assumption was made by the user. A possible solution would be to flip quick link 1 and quick link 2, i.e. the first quick link becomes:
"Global AT Innovation Insights →"
