### ISSUE TITLE
Bug report: Getting stuck on map using touchpad 

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#11]
## The problem

I was using the touchpad. When the map appeared on the screen, I should move the mouse outside the map to scroll down the whole page. Otherwise it would only zoom in and out the map.

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

1. Go to Home page
2. Click on  scrol to the map, zoom in, pan around, zoom out.  Continue scrolling up or down the homepage.
3. Scroll down to the map, zoom in, pan around, zoom out.  Continue scrolling up or down the homepage.

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Mac OS
 - Browser Chrome
 - Version 

**Smartphone (please complete the following information):**

**Additional context**

## The expectation

The user should be able to freely jump onto, and off, the map without getting stuck

**Comment by matthew-gibbs** [comment]
I suppose we could disable scroll on the map - and direct them to the buttons to zoom in and out?

**Comment by Daniel-UCL** [comment]
If that’s a fix for mobile?! Let’s do it. Any reasons why it’s a bad idea? Would it negatively impact the desktop UX? Might be aa decision based on device analytics. My feeling from the testing we have done is that we’d win more on mobile, than lose on desktop.
