### ISSUE TITLE
Bug report: Confused by ID number in AT filter

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#13]
## The problem

Needs to be removed as they do not refer to any value

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Mac OS
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

## The expectation

AT types should be a clear label

**Comment by matthew-gibbs** [comment]
Part of the dataset. I can either trim it in code, or we can change the data

**Comment by Daniel-UCL** [comment]
Which would be the more stable, and less time consuming solution? I’m okay with changing the local copy of the data, rather than complicating the parsing by additional trims. I assume adding a script to trim might throw errors, if we were to remove the ID from the data later. I think the data will need to be edited anyway. So we might as well start by deleting the strings. Open for discussion though.
