### ISSUE TITLE
Bug report: Filter should not clear after opening “explore publication” link. 

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#14]
## The problem
'When returning from an external link, the filters clear.

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

1. Go to Country pages
2. Click on expore publications

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Mac OS
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

## The expectation

The external link should open in a new tab or window, so when I return to the country page, the filter does not reset to its default.

**Comment by matthew-gibbs** [comment]
Probably solved by opening the publications in another tab as described in another issue

**Comment by Daniel-UCL** [comment]
Yes, let’s try. Two birds with one stone.

**Comment by Saferrei** [comment]
Issue has been fixed.
