### ISSUE TITLE
Bug report: Fragmented text when reading with voice over.  

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#15]
## The problem
The country summary text is very fragmented when read with Voice Over on MacOS Chrome. The RATA and AT abreviations are enclosed in a div group, which splits up the paragraph into chunks.

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Mac OS
 - Browser: Chrome
 - Version 

**Smartphone (please complete the following information):**

**Additional context**

## The expectation

The text should read as one paragraph without the Interruption of other html elements e.g., div elements with aria labels.

**Comment by matthew-gibbs** [comment]
The code for the abstract is below. It's not a div, it's an `abbr` element. Perhaps including them in long form will make the readability better? 
```
<span id="js-abstract" class="abstract">Saudi Arabia has <b>3</b> published studies, <b>0</b> national survey(s), <b>0</b> cohort(s), and <b>has not</b> conducted a <abbr title="rapid Assistive Technology Assessment">rATA</abbr> survey including <abbr title="Assistive Technology">AT</abbr> data.</span>
```

**Comment by Daniel-UCL** [comment]
Ahh! I like the idea of abbreviation elements, in theory. It’s new to me. However, in practice, assuming fairly default screen reader behaviour (VO specifically), I think


`<abbr title="rapid Assistive Technology Assessment">rATA</abbr>`

Breaks the flow of reading too much. Behaves like a `<div>` with an `aria-label`, introducing too many regions within the page. I’d prefer to not use `<abbr>` in the interest of screen reader experience. Happy to test the behaviour of an alternative element, if we have options. Otherwise, let’s just use the long form.


Dr Daniel Hajas | Innovation Manager | Global Disability Innovation Hub<http://www.disabilityinnovation.com>
***@***.******@***.***> | +44 (0) 7810736983 | www.disabilityinnovation.com<http://www.disabilityinnovation.com> | Twitter @GDIHub<https://twitter.com/GDIHub> | at2030.org<http://www.at2030.org>

Zoom: Enter my waiting room<https://ucl.zoom.us/j/8621722789?pwd=RUxiUFBveTFwemdlSDY5R3Z4SVBWdz09>
Calendar: Book a meeting<https://calendly.com/dh256>
README: Please note, I have a README<https://dh256git.github.io/work/> page on how I work most productively, considering my accessibility requirements, workflow preferences, and work culture.

Global Disability Innovation (GDI) Hub is a UCL based academic research & practice centre accelerating disability innovation for a fairer world.

[cid:97023edf-36da-4495-9f94-1f0b154ac8c3]
Graphic with title 'Innovation, Insight, Impact' & logos: GDI Hub, UCL, AT2030, WHO Collaborating Centre, GDI Accelerate.

On 11 Jul 2023, at 09:48, Matt Gibbs ***@***.******@***.***>> wrote:


⚠ Caution: External sender



The code for the abstract is below. It's not a div, it's an abbr element. Perhaps including them in long form will make the readability better?

<span id="js-abstract" class="abstract">Saudi Arabia has <b>3</b> published studies, <b>0</b> national survey(s), <b>0</b> cohort(s), and <b>has not</b> conducted a <abbr title="rapid Assistive Technology Assessment">rATA</abbr> survey including <abbr title="Assistive Technology">AT</abbr> data.</span>

**Comment by Daniel-UCL** [comment]
Issue is not trivial to reproduce, but it has been fixed where possible.
