### ISSUE TITLE
Bug report: Mistake in copy of RATA (Kenya) 

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#16]
## The problem
In the text explaining that RATA has been done in Kenya, the word "sample" appears twice.

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Mac OS
 - Browser Chrome,
 - Version 

**Smartphone (please complete the following information):**

**Additional context**

## The expectation
Typo needs fixing.

**Comment by matthew-gibbs** [comment]
Will be in the data - I can amend.

**Comment by Daniel-UCL** [comment]
Easy. Let’s do that. I’m happy to verify and close issue after it’s done.

**Comment by Saferrei** [comment]
Issue is fixed.
