### ISSUE TITLE
Bug report: Typo on RATA tab panel 

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#17]
## The problem
The "general inquiries" link in the RATA tab has a typo. A missing "I".

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Mac OS
 - Browser: Chrome,

**Smartphone (please complete the following information):**

**Additional context**

## The expectation

Typo needs fixing

**Comment by Saferrei** [comment]
Issue seems to be fixed.
