### ISSUE TITLE
Bug report: Unable to clear AT filter

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#19]
## The problem
I'm unable to clear the AT filter after I selected a specific AT.

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Mac OS
 - Browser Chrome
 - Version 
 
**Smartphone (please complete the following information):**

**Additional context**
I can only select another AT, but not clear the filter. Once I also select a country, I can clear the country filter by clicking "clear filters".

## The expectation

The "clear filters" button should either clear both filters, or there should be a button for each filter, clearing them individually.

**Comment by Saferrei** [comment]
There is a separate button to clear country filter, but there is no button to clear the AT filter.
