### ISSUE TITLE
Feature request: Global country filter should return global stats for all AT type, while new "world-wide" country filter option shows multinational studies. 

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#2]
## The problem

"wheelchairs" is not an option in the dropdown menu after choosing "global" Also, the 'global' option be moved to the top instead of in the country list will be better

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

1. Go to Home page
2. Click on the top navigation, click "home and insights". Select "data by country". Filter by "global". In the "select AT" filter by wheelchairs.

**Add screenshots**
![Picture2](https://github.com/Daniel-GDI-Hub/data-portal/assets/133969226/3ecfc17e-1a1d-4d77-9a47-5b138debc434)

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser Chrome
 - Version 

**Smartphone (please complete the following information):**

**Additional context**
After selecting "Global", there is no result for wheelchair. Also, I never consider "Global" as country, so it may become the default selection and shown at the top of the list to show users they can search by Global scale.

## The expectation

The results page shows a summary of AT indicators for wheelchairs at the global level, with a list of country specific entries below.

**Comment by matthew-gibbs** [comment]
Similar to previous issue, in the dataset, 'Global' is listed as a country, and pertains to studies which have been conducted globally, rather than an abstraction we have created. One to discuss, but currently, the representation on the platform is the same as the dataset :)

**Comment by Daniel-UCL** [comment]
Yes, this is a small redesign / rethink of how we use the data set. We would like to preserve “global” as a special type of “country” serving as a data structure for data on global need, access, prevalence of specific disability type. Likely this can come from a separate data sheet. The current “global” term in the data set should be renamed to “multinational” or “world-wide”, referring to aggregate data from multiple countries. Global should also be pulled to the front of the list, rather than lost in the alphabet, serving as a default :)

**Comment by Daniel-UCL** [comment]
Partially addressed. World-wide country option now shows multinational studies, while new default option of "global" shows all the available data. This, still does not show global stats per AT, but this info is available on the data by AT page, so we decided to leave it as it is for the time being.
