### ISSUE TITLE
Bug report: AT filter option "distance" does not make sense

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#20]
## The problem

The menu options in some cases include "distance" as a type of AT. Makes no sense.

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Mac OS
 - Browser : Chrome
 - Version 

**Smartphone (please complete the following information):**

**Additional context**

## The expectation
The AT filter options should be a sensible list of options.

**Comment by dh256git** [comment]
Looks fixed, happy to close the issue.
