### ISSUE TITLE
Bug report: Incorrect abbreviation 

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#21]
## The problem
DPO is translated to "Data protection officers" and not "disabled people's organisations".This may only happen for screen reader users.

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Mac OS
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**
tested with voice over

## The expectation

**What is the expected behaviour?**

See problem

**Comment by Saferrei** [comment]
Abbreviation is no longer read. Voiceover only says DPO.

**Comment by Daniel-UCL** [comment]
On Chrome, on the home page, the original issue is fixed i.e. “Data Protection Officer” is corrected to “Disabled People’s Organisations” but the actual `<abrv>` tag still needs to be removed for improved experience. Safari does not interpret `<abrv>` so it’s not a problem there.
