### ISSUE TITLE
Bug report: improve Olli visualisation view

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#23]
## The problem

The current implementation could be improved by newer versions of the Olli library, and probably by defining the underlying Vega spec differently.

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Mac OS
 - Browser : Chrome
 - Version 

**Smartphone (please complete the following information):**

**Additional context**

## The expectation

The legend should be more descriptive, and summary data should be available every year.

**Comment by matthew-gibbs** [comment]
Hey @Daniel-GDI-Hub - I have looked at the Olli page on NPM, and it seems that the latest version is 1.0.7. That is the version we have in the build. Is there a newer version I'm missing? :D
