### ISSUE TITLE
Bug report: Clearing country filter and improving data display on the map

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#3]
## The problem
No 'clear filters' shown. Can read the available data types and number of data entries. Would be better to show the country name when zooming in

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

1. Go to Home page
2. Click on Clear the "global" country filter to return to the "home and insights" page. On the map, pan and zoom until you can read off the available types of data for India.

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser Chrome,

**Smartphone (please complete the following information):**

**Additional context**

## The expectation

**What is the expected behaviour?**

The map shows available data types and number of data entries.

**Comment by matthew-gibbs** [comment]
Do you mean label the country on the map itself? We can certainly look at doing that. Good spot on the clear filters too.

**Comment by Daniel-UCL** [comment]
Yes. Let’s try. Low priority though.

**Comment by Saferrei** [comment]
Countries are named if they are clicked. Names are not yet shown if you zoom in. Clear filters button is working. When you click on a specific country the number of entries aren't shown yet.
