### ISSUE TITLE
Feature request: Explore publications on country pages (Ex. Kenya)

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#4]
## The problem
Successfully jump to the external website but did not open a new window

## The solution
The "explore publication" link will open an external website, containing the publication itself. Closing the external site will return the browser to the country page you started from (Kenya).

## The alternatives

**Describe alternatives you've considered**

## Additional info

On Country pages, scroll down to one of three publications. Click the "explore publication" link at the end of the data entry. Browse the publication page, then return to the Kenya country page by closing the window.

**Comment by matthew-gibbs** [comment]
Ah, so open the publication links in a new tab?

**Comment by Daniel-UCL** [comment]
Yes! A simple `target=“_blank" rel=“noopener noreferrer” `should solve this issue.

**Comment by Saferrei** [comment]
This issue seems to be fixed.
