### ISSUE TITLE
Bug report: View data availability for AT in the selected country

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#5]
## The problem
The country option is cleared as I change the At filter to 'limb prosthetics'. I prefer an obvious indicator to show no data in the selected country.  

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

1. Go to AT pages
2. Click on Filter wheelchair data by country. Select the United Kingdom option in the country filter. View the AT indicators to determine the number of studies published. Change the AT filter to "limb prosthetics". Verify that data is shown for the UK. 

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser Chrome,
 - Version 

**Smartphone (please complete the following information):**

**Additional context**
When I selected a country(UK) and then changed the AT from wheelchair to limb prosthetics, I supposed the country I selected didn't change, but in fact it cleared the country selection because there was no data for this country. At first, I thought the results were all in the UK, but it turned out there was no data in the UK without showing me a notice.

## The expectation

The results page shows a notice of no data available for limb prosthetics in the UK, or shows a list of available data entries.

**Comment by matthew-gibbs** [comment]
Is this on the 'data by AT' or 'data by country' page? In theory it shouldn't be possible to select a country, then select an AT with no data on the data by country page, as subfilters only show ones with data.

In theory it would be possible to do this on the data by AT page, but that would mean changing the top level filter. 
![image](https://github.com/Daniel-GDI-Hub/data-portal/assets/19665116/789ec8b5-a719-45bb-a81a-4b965ba83213)

**Comment by Daniel-UCL** [comment]
The issue describes behaviour on the “data by AT” page. Current behaviour is as such:

1. Set AT filter to wheelchairs,
2. Set country filter to UK,
3. Results are shown (15).
4. User wants to see data in the UK, with regards to a different AT, for example limb prosthetics, so changes AT filter,
5. The country filter clears (because no data is available in the UK for limb prosthetics). Existing data (2) from the entire country list is shown for limb prosthetics.

Desired behaviour:

1. Set AT filter to wheelchairs,
2. Set country filter to UK,
3. Results are shown (15).
4. User wants to see data in the UK, with regards to a different AT, for example limb prosthetics,
5. The country filter remains fixed on UK. The page content should
 - display a message that data is not available for limb prosthetics in the UK,
 - display global data for limb prosthetics, and
 - prompt the user to either select a country where data on limb prosthetics is available, or a new type of AT in the UK.
