### ISSUE TITLE
Bug report: Clear filters is misleading

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#6]
## The problem

Only the country filter is cleared

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

1. Go to AT pages
2. Click on 'Find the country filter dropdown menu. Click the "clear filters" button.

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser Chrome
 - Version 

**Smartphone (please complete the following information):**

**Additional context**

## The expectation
The clear filter option clears both the AT filter and the country filter, returning to the default state of these filters.

**Comment by matthew-gibbs** [comment]
True, because on the data by AT page, there's always a AT selected, and on the data by country page, there's always a country selected, otherwise the default would (currently) need to be blank pages. 

Two possible solutions exist:
1. By default show _everything_ - but this would be super intensive on loads.
2. Rename to 'Clear AT filter' and 'Clear country filter' respectively

**Comment by Daniel-UCL** [comment]
Let’s go with solution 2: Rename to 'Clear AT filter' and 'Clear country filter' respectively

**Comment by Saferrei** [comment]
Clear country filter button has been changed and works, but a second problem has popped up. After choosing an AT type and then the country the button appears as correctly prompted. But when you change the AT type to something else and the country drop box goes back to default, the clear the country filter button remains there even though the drop box is now blank. This may not be an issue later if the country filter remains there, but I thought it would be best to let you know.

**Comment by Saferrei** [comment]
![image](https://github.com/Daniel-GDI-Hub/data-portal/assets/140531084/f7f59c1a-556f-4669-9790-ccab36ebe66c)

**Comment by Saferrei** [comment]
I have just checked and the same thing happens in the data by country section.
