### ISSUE TITLE
Bug report: Browser inconpatibility (Safri and Firefox)

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#7]
## The problem
With Safari, the drop down box does not appear in the Select Country area, and the Country summary area keeps showing loading, but I have tried it with Chorme without this problem.

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

1. Go to Country pages
2. Click on In the top menu, open the "data by country" menu item, and in the country filter select Kenya.

**Add screenshots**

**Desktop (please complete the following information):**

 - OS: Mac OS
 - Browser Safari

**Smartphone (please complete the following information):**

**Additional context**

## The expectation

The country page shows a summary of data types available with a tab group, and the default "publications" tab opened underneath the summary.

**Comment by matthew-gibbs** [comment]
Really strange! I wonder why

**Comment by Daniel-UCL** [comment]
This is the number 1 big boss priority in the bug fixing game. The portal was working fine in Safari and FIreFox before migrating to the new domain, i.e. on Surge it was fine. Something to do with that? Solutions would be much appreciated :)

**Comment by Saferrei** [comment]
The drop down box is now working on Safari for the data by country section.

**Comment by Daniel-UCL** [comment]
Resolved issue with javascript.
