### ISSUE TITLE
Bug report: Error in visulisation of survey waves

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#8]
## The problem

A error in 2009 - 2010, where there is a line in the survey wave.

## Help us reproduce the problem

**Steps to reproduce the behaviour:**

1. Go to Home page
2. Click on View the embedded visualisation. Determine how many new data sets were published between 2000 and 2020.

**Add screenshots**
![Picture3](https://github.com/Daniel-GDI-Hub/data-portal/assets/133969226/0d3f6627-94ab-4282-9812-cb8facf96fca)

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser Chrome
 - Version 

**Smartphone (please complete the following information):**

**Additional context**

## The expectation

The visualisation shows three data types, as a time series chart.

**Comment by matthew-gibbs** [comment]
Interesting, I wonder if this is a data thing or a vega thing

**Comment by Daniel-UCL** [comment]
We found the issue with the data duplication.
