### ISSUE TITLE
Feature request: Update summany text after filtering 

### ISSUE THREAD

**Issue by Daniel-UCL** [Daniel-GDI-Hub/data-portal#9]
## The problem
Although the result changes, there is still a line that says 15 studies have been published on Wheelchairs, which confused me for its the result for UK.

## The solution
The  summary text should reflect the changes after filtering. The number of results displayed reduces from 15 to only 1, displaying the relevant entry for the UK.

## The alternatives

**Describe alternatives you've considered**

## Additional info

From the top navigation bar, open the "data by Assistive Tech" menu item. In the AT dropdown menu, filter by "wheelchairs".Filter wheelchair data by country. Select the United Kingdom option in the country filter. View the AT indicators to determine the number of studies published.

**Comment by Saferrei** [comment]
This issue has been fixed.
